options = {
	["VR"] = {
		["box_mouse_cursor"] = true,
		["enable"] = true,
		["pixel_density"] = 1,
		["use_mouse"] = false,
	},
	["difficulty"] = {
		["avionicsLanguage"] = "native",
		["birds"] = 200,
		["cockpitLanguage"] = "english",
		["cockpitStatusBarAllowed"] = false,
		["cockpitVisualRM"] = false,
		["easyCommunication"] = true,
		["easyFlight"] = false,
		["easyRadar"] = false,
		["externalViews"] = true,
		["fuel"] = false,
		["geffect"] = "realistic",
		["hideStick"] = false,
		["iconsTheme"] = "nato",
		["immortal"] = false,
		["impostors"] = "large",
		["labels"] = true,
		["map"] = true,
		["miniHUD"] = false,
		["optionsView"] = "optview_all",
		["padlock"] = true,
		["permitCrash"] = true,
		["radio"] = false,
		["reports"] = true,
		["setGlobal"] = true,
		["spectatorExternalViews"] = true,
		["tips"] = true,
		["units"] = "metric",
		["userSnapView"] = true,
		["weapons"] = false,
	},
	["graphics"] = {
		["DOF"] = 0,
		["HDR"] = 0,
		["LensEffects"] = 3,
		["MSAA"] = 1,
		["OculusRift"] = false,
		["TranspSSAA"] = false,
		["anisotropy"] = 4,
		["aspect"] = 1.7777777777778,
		["civTraffic"] = "medium",
		["clutterMaxDistance"] = 700,
		["cockpitShadows"] = true,
		["color"] = "32",
		["disableAero"] = false,
		["effects"] = 3,
		["flatTerrainShadows"] = 0,
		["fullScreen"] = true,
		["haze"] = 1,
		["heatBlr"] = 1,
		["height"] = 1080,
		["lights"] = 2,
		["multiMonitorSetup"] = "1camera",
		["preloadRadius"] = 150000,
		["scenes"] = "high",
		["shadowTree"] = false,
		["shadows"] = 2,
		["sync"] = false,
		["terrainTextures"] = "min",
		["textures"] = 2,
		["treesVisibility"] = 9000,
		["visibRange"] = "High",
		["water"] = 2,
		["width"] = 1920,
	},
	["miscellaneous"] = {
		["Coordinate_Display"] = "Lat Long",
		["F2_view_effects"] = 1,
		["TrackIR_external_views"] = true,
		["accidental_failures"] = false,
		["f10_awacs"] = true,
		["f11_free_camera"] = true,
		["f5_nearest_ac"] = true,
		["force_feedback_enabled"] = true,
		["headmove"] = false,
		["show_pilot_body"] = false,
		["synchronize_controls"] = false,
	},
	["plugins"] = {
		["A-10C"] = {
			["CPLocalList"] = "default",
		},
		["Su-25T"] = {
			["CPLocalList"] = "default",
		},
		["TF-51D"] = {
			["CPLocalList"] = "default",
			["assistance"] = 100,
			["autoRudder"] = false,
		},
	},
	["sound"] = {
		["GBreathEffect"] = true,
		["cockpit"] = 0,
		["gui"] = 0,
		["headphones"] = 0,
		["hear_in_helmet"] = false,
		["music"] = -12,
		["radioSpeech"] = true,
		["subtitles"] = true,
		["volume"] = 0,
		["world"] = 0,
	},
	["views"] = {
		["cockpit"] = {
			["avionics"] = 1,
			["mirrors"] = false,
			["reflections"] = false,
			["russianHud"] = false,
		},
	},
}
